version: "3.8"

services:
    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydb
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    mongodb:
        image: mongo:6
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
        depends_on:
            - mongodb

volumes:
    mysql-data:
    mongo-data:
